# Generated by Django 5.0.2 on 2025-02-26 01:37

import django.core.validators
import django.db.models.deletion
import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('receipt', 'Квитанция об оплате'), ('chat', 'Скриншот чата')], max_length=20, verbose_name='Тип документа')),
                ('file', models.FileField(upload_to=orders.models.order_document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg'])], verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Время загрузки')),
            ],
            options={
                'verbose_name': 'Документ заказа',
                'verbose_name_plural': 'Документы заказа',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_from', models.DecimalField(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator('0.00000001')], verbose_name='Сумма обмена')),
                ('amount_to', models.DecimalField(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator('0.00000001')], verbose_name='Сумма к получению')),
                ('rate', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Курс обмена')),
            ],
            options={
                'verbose_name': 'Элемент заказа',
                'verbose_name_plural': 'Элементы заказа',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Оценка не может быть меньше 1'), django.core.validators.MaxValueValidator(5, message='Оценка не может быть больше 5')], verbose_name='Оценка')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Отображать на сайте')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(blank=True, max_length=10, unique=True, verbose_name='Код отслеживания')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('processing', 'В обработке'), ('waiting_delivery', 'Ожидает выдачу'), ('completed', 'Выполнен'), ('cancelled', 'Отменён')], default='new', max_length=20, verbose_name='Статус')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('telegram', models.CharField(blank=True, max_length=50, verbose_name='Telegram')),
                ('needs_delivery', models.BooleanField(default=False, verbose_name='Требуется доставка')),
                ('delivery_address', models.TextField(blank=True, null=True, verbose_name='Адрес доставки')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='exchange.exchangeoffice', verbose_name='Обменный пункт')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
    ]
