# Generated by Django 5.0.14 on 2025-07-13 14:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0002_initial"),
        ("core", "0001_initial"),
        ("exchange", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount_from",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator("0.0001")],
                        verbose_name="Сумма к обмену",
                    ),
                ),
                (
                    "amount_to",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator("0.0001")],
                        verbose_name="Сумма к получению",
                    ),
                ),
                (
                    "applied_rate",
                    models.DecimalField(
                        decimal_places=8, max_digits=15, verbose_name="Примененный курс"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает обработки"),
                            ("completed", "Выполнен"),
                            ("canceled", "Отменён"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "delivery",
                    models.BooleanField(default=False, verbose_name="Доставка"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Завершен"
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="branches.branch",
                        verbose_name="Филиал",
                    ),
                ),
                (
                    "currency_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders_from",
                        to="exchange.currency",
                        verbose_name="Из валюты",
                    ),
                ),
                (
                    "currency_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders_to",
                        to="exchange.currency",
                        verbose_name="В валюту",
                    ),
                ),
                (
                    "delivery_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_orders",
                        to="core.address",
                        verbose_name="Адрес доставки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "db_table": "orders",
                "ordering": ["-created_at"],
            },
        ),
    ]
