# Generated by Django 5.1.4 on 2024-12-24 22:58

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='from_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма исходной валюты'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='rate',
            field=models.DecimalField(decimal_places=6, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='Курс обмена'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='to_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма целевой валюты'),
        ),
    ]
