# Generated by Django 5.0.2 on 2025-02-26 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchange', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='orderdocument',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='orderdocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто загрузил'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='from_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchanges_from', to='exchange.currency', verbose_name='Из валюты'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='to_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchanges_to', to='exchange.currency', verbose_name='В валюту'),
        ),
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AlterUniqueTogether(
            name='orderdocument',
            unique_together={('order', 'document_type')},
        ),
    ]
