# Generated by Django 5.0.14 on 2025-07-22 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Комментарий пользователя или оператора к заказу",
                verbose_name="Комментарий",
            ),
        ),
    ]
