# Generated by Django 5.1.4 on 2025-01-04 18:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_from_amount_alter_orderitem_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_from_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Общая сумма исходной валюты'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_to_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Общая сумма целевой валюты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in format: '+999999999'", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон клиента'),
        ),
    ]
