CREATE TABLE "users" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "username" varchar,
  "email" varchar UNIQUE NOT NULL,
  "first_name" varchar,
  "last_name" varchar,
  "whatsapp" bigint NOT NULL,
  "telegram" varchar,
  "address_id" int,
  "referral_code" varchar UNIQUE NOT NULL,
  "referred_by_code" varchar,
  "role" varchar NOT NULL DEFAULT 'user',
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "addresses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "country" varchar,
  "city" varchar,
  "street" varchar,
  "house_number" varchar,
  "postal_code" varchar,
  "full_address" text NOT NULL,
  "latitude" decimal,
  "longitude" decimal,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "branches" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "email" varchar UNIQUE,
  "whatsapp" bigint,
  "telegram" varchar,
  "instagram" varchar,
  "address_id" int NOT NULL,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "branch_hours" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "branch_id" int,
  "weekday" int NOT NULL,
  "open_time" time,
  "close_time" time,
  "is_open" boolean DEFAULT true
);

CREATE TABLE "currencies" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar UNIQUE NOT NULL,
  "name" varchar UNIQUE NOT NULL,
  "symbol" varchar,
  "decimal_places" int DEFAULT 2,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "branch_currencies" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "branch_id" int,
  "currency_id" int,
  "amount" decimal NOT NULL DEFAULT 0
);

CREATE TABLE "exchange_rates" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "currency_from_id" int,
  "currency_to_id" int,
  "branch_id" int,
  "min_amount" decimal NOT NULL,
  "max_amount" decimal,
  "rate" decimal NOT NULL,
  "is_hot" boolean DEFAULT false,
  "visible" boolean DEFAULT true,
  "in_filter" boolean DEFAULT false,
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "orders" (
  "id" SERIAL PRIMARY KEY,
  "user_id" uuid,
  "branch_id" int,
  "currency_from_id" int,
  "currency_to_id" int,
  "amount_from" decimal NOT NULL,
  "amount_to" decimal NOT NULL,
  "applied_rate" decimal NOT NULL,
  "status" varchar NOT NULL DEFAULT 'pending',
  "delivery" boolean DEFAULT false,
  "delivery_address_id" int,
  "completed_at" timestamp
);

CREATE TABLE "reviews" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid,
  "order_id" uuid,
  "rating" int NOT NULL,
  "comment" text,
  "visible" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "referral_transactions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid,
  "referred_user_id" uuid,
  "order_id" int,
  "amount" decimal NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE UNIQUE INDEX ON "branch_hours" ("branch_id", "weekday");

CREATE UNIQUE INDEX ON "branch_currencies" ("branch_id", "currency_id");

CREATE UNIQUE INDEX ON "exchange_rates" ("currency_from_id", "currency_to_id", "branch_id", "min_amount");

CREATE UNIQUE INDEX ON "reviews" ("user_id", "order_id");

ALTER TABLE "users" ADD FOREIGN KEY ("address_id") REFERENCES "addresses" ("id");

ALTER TABLE "branches" ADD FOREIGN KEY ("address_id") REFERENCES "addresses" ("id");

ALTER TABLE "branch_hours" ADD FOREIGN KEY ("branch_id") REFERENCES "branches" ("id");

ALTER TABLE "branch_currencies" ADD FOREIGN KEY ("branch_id") REFERENCES "branches" ("id");

ALTER TABLE "branch_currencies" ADD FOREIGN KEY ("currency_id") REFERENCES "currencies" ("id");

ALTER TABLE "exchange_rates" ADD FOREIGN KEY ("currency_from_id") REFERENCES "currencies" ("id");

ALTER TABLE "exchange_rates" ADD FOREIGN KEY ("currency_to_id") REFERENCES "currencies" ("id");

ALTER TABLE "exchange_rates" ADD FOREIGN KEY ("branch_id") REFERENCES "branches" ("id");

ALTER TABLE "orders" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "orders" ADD FOREIGN KEY ("branch_id") REFERENCES "branches" ("id");

ALTER TABLE "orders" ADD FOREIGN KEY ("currency_from_id") REFERENCES "currencies" ("id");

ALTER TABLE "orders" ADD FOREIGN KEY ("currency_to_id") REFERENCES "currencies" ("id");

ALTER TABLE "orders" ADD FOREIGN KEY ("delivery_address_id") REFERENCES "addresses" ("id");

ALTER TABLE "reviews" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "reviews" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");

ALTER TABLE "referral_transactions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "referral_transactions" ADD FOREIGN KEY ("referred_user_id") REFERENCES "users" ("id");

ALTER TABLE "referral_transactions" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");
