# Generated by Django 5.0.2 on 2025-02-03 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код валюты')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('symbol', models.CharField(max_length=5, verbose_name='Символ')),
                ('decimal_places', models.PositiveSmallIntegerField(default=2, help_text='Количество знаков после запятой для отображения и расчетов', verbose_name='Знаков после запятой')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.CreateModel(
            name='ExchangeOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Обменный пункт',
                'verbose_name_plural': 'Обменные пункты',
            },
        ),
        migrations.CreateModel(
            name='CurrencyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Баланс')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.currency', verbose_name='Валюта')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='exchange.exchangeoffice', verbose_name='Обменный пункт')),
            ],
            options={
                'verbose_name': 'Баланс валюты',
                'verbose_name_plural': 'Балансы валют',
                'unique_together': {('office', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс')),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Минимальная сумма')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_from', to='exchange.currency', verbose_name='Из валюты')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_to', to='exchange.currency', verbose_name='В валюту')),
            ],
            options={
                'verbose_name': 'Курс обмена',
                'verbose_name_plural': 'Курсы обмена',
                'unique_together': {('from_currency', 'to_currency')},
            },
        ),
    ]
