# Generated by Django 5.1.4 on 2024-12-24 20:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код валюты')),
                ('name', models.CharField(max_length=50, verbose_name='Название валюты')),
                ('symbol', models.CharField(max_length=5, verbose_name='Символ валюты')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название филиала')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base_branches', to='exchange.currency', verbose_name='Базовая валюта')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма')),
                ('average_purchase_rate', models.DecimalField(decimal_places=6, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Средний курс покупки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_balances', to='exchange.branch', verbose_name='Филиал')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='exchange.currency', verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Баланс валюты',
                'verbose_name_plural': 'Балансы валют',
                'ordering': ['branch', 'currency'],
                'unique_together': {('branch', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Курс обмена')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Минимальная сумма')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='exchange.branch', verbose_name='Филиал')),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_rates', to='exchange.currency', verbose_name='Исходная валюта')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_rates', to='exchange.currency', verbose_name='Целевая валюта')),
            ],
            options={
                'verbose_name': 'Курс обмена',
                'verbose_name_plural': 'Курсы обмена',
                'ordering': ['branch', 'from_currency', 'to_currency'],
                'unique_together': {('branch', 'from_currency', 'to_currency')},
            },
        ),
    ]
