# Generated by Django 5.0.14 on 2025-07-16 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Код валюты"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "symbol",
                    models.CharField(blank=True, max_length=5, verbose_name="Символ"),
                ),
                (
                    "decimal_places",
                    models.PositiveSmallIntegerField(
                        default=2, verbose_name="Знаков после запятой"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
            ],
            options={
                "verbose_name": "Валюта",
                "verbose_name_plural": "Валюты",
                "db_table": "currencies",
            },
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="Минимальная сумма",
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=15,
                        null=True,
                        verbose_name="Максимальная сумма",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=8, max_digits=15, verbose_name="Курс"
                    ),
                ),
                (
                    "is_hot",
                    models.BooleanField(default=False, verbose_name="Горячий курс"),
                ),
                ("visible", models.BooleanField(default=False, verbose_name="Видимый")),
                (
                    "in_filter",
                    models.BooleanField(default=False, verbose_name="В фильтрах"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchange_rates",
                        to="branches.branch",
                        verbose_name="Филиал",
                    ),
                ),
                (
                    "currency_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates_from",
                        to="exchange.currency",
                        verbose_name="Из валюты",
                    ),
                ),
                (
                    "currency_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates_to",
                        to="exchange.currency",
                        verbose_name="В валюту",
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс обмена",
                "verbose_name_plural": "Курсы обмена",
                "db_table": "exchange_rates",
            },
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_from",
                    models.DecimalField(
                        decimal_places=4, max_digits=15, verbose_name="Сумма к оплате"
                    ),
                ),
                (
                    "amount_to",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="Сумма к получению",
                    ),
                ),
                (
                    "applied_rate",
                    models.DecimalField(
                        decimal_places=8, max_digits=15, verbose_name="Примененный курс"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Источник"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Примечание")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="branches.branch",
                        verbose_name="Филиал",
                    ),
                ),
                (
                    "currency_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases_from",
                        to="exchange.currency",
                        verbose_name="Чем заплатили",
                    ),
                ),
                (
                    "currency_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases_to",
                        to="exchange.currency",
                        verbose_name="Что купили",
                    ),
                ),
            ],
            options={
                "verbose_name": "Закупка валюты",
                "verbose_name_plural": "Закупки валют",
                "db_table": "purchases",
                "ordering": ["-created_at"],
            },
        ),
    ]
