# Generated by Django 5.0.14 on 2025-07-14 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0003_branchcurrency_avg_purchase_rate"),
        ("exchange", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_from",
                    models.DecimalField(
                        decimal_places=4, max_digits=15, verbose_name="Сумма к оплате"
                    ),
                ),
                (
                    "amount_to",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="Сумма к получению",
                    ),
                ),
                (
                    "applied_rate",
                    models.DecimalField(
                        decimal_places=8, max_digits=15, verbose_name="Примененный курс"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Источник"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Примечание")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="branches.branch",
                        verbose_name="Филиал",
                    ),
                ),
                (
                    "currency_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases_from",
                        to="exchange.currency",
                        verbose_name="Чем заплатили",
                    ),
                ),
                (
                    "currency_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases_to",
                        to="exchange.currency",
                        verbose_name="Что купили",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Закупка валюты",
                "verbose_name_plural": "Закупки валют",
                "db_table": "purchases",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["branch", "currency_to"],
                        name="purchases_branch__ded84a_idx",
                    )
                ],
            },
        ),
    ]
