# Generated by Django 5.0.2 on 2025-02-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Код валюты'),
        ),
    ]
