# Generated by Django 5.0.14 on 2025-07-16 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exchange", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="exchangerate",
            unique_together={("currency_from", "currency_to", "branch", "min_amount")},
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(
                fields=["branch", "currency_to"], name="purchases_branch__ded84a_idx"
            ),
        ),
    ]
