# Generated by Django 5.0.14 on 2025-07-15 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0002_purchase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchangerate",
            name="visible",
            field=models.BooleanField(default=False, verbose_name="Видимый"),
        ),
    ]
