# Generated by Django 5.0.14 on 2025-07-16 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "whatsapp",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="WhatsApp"
                    ),
                ),
                (
                    "telegram",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Telegram"
                    ),
                ),
                (
                    "instagram",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Instagram"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
            ],
            options={
                "verbose_name": "Филиал",
                "verbose_name_plural": "Филиалы",
                "db_table": "branches",
            },
        ),
        migrations.CreateModel(
            name="BranchCurrency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=15,
                        verbose_name="Количество",
                    ),
                ),
            ],
            options={
                "verbose_name": "Валюта филиала",
                "verbose_name_plural": "Валюты филиалов",
                "db_table": "branch_currencies",
            },
        ),
        migrations.CreateModel(
            name="BranchHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Воскресенье"),
                            (1, "Понедельник"),
                            (2, "Вторник"),
                            (3, "Среда"),
                            (4, "Четверг"),
                            (5, "Пятница"),
                            (6, "Суббота"),
                        ],
                        verbose_name="День недели",
                    ),
                ),
                (
                    "open_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Время открытия"
                    ),
                ),
                (
                    "close_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Время закрытия"
                    ),
                ),
                ("is_open", models.BooleanField(default=True, verbose_name="Открыт")),
            ],
            options={
                "verbose_name": "График работы филиала",
                "verbose_name_plural": "Графики работы филиалов",
                "db_table": "branch_hours",
            },
        ),
    ]
