# Generated by Django 5.0.14 on 2025-07-13 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
        ("exchange", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="branchcurrency",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="exchange.currency",
                verbose_name="Валюта",
            ),
        ),
        migrations.AddField(
            model_name="branchhours",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hours",
                to="branches.branch",
                verbose_name="Филиал",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="branchcurrency",
            unique_together={("branch", "currency")},
        ),
        migrations.AlterUniqueTogether(
            name="branchhours",
            unique_together={("branch", "weekday")},
        ),
    ]
