# Generated by Django 5.0.14 on 2025-07-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="branchcurrency",
            name="avg_purchase_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=15,
                null=True,
                verbose_name="Средняя себестоимость",
            ),
        ),
    ]
