# Generated by Django 5.0.14 on 2025-07-22 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0003_initial"),
        ("core", "0005_remove_address_full_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branches",
                to="core.address",
                verbose_name="Адрес филиала",
            ),
        ),
        migrations.AlterField(
            model_name="branch",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="branch",
            name="instagram",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Instagram"
            ),
        ),
        migrations.AlterField(
            model_name="branch",
            name="telegram",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Telegram"
            ),
        ),
        migrations.AlterField(
            model_name="branchhours",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hours",
                to="branches.branch",
                verbose_name="Филиал",
            ),
        ),
    ]
