# Generated by Django 5.0.14 on 2025-07-15 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0003_branchcurrency_avg_purchase_rate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branchcurrency",
            name="avg_purchase_rate",
        ),
        migrations.AlterField(
            model_name="branch",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email"),
        ),
    ]
