# Generated by Django 5.0.14 on 2025-07-14 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0003_branchcurrency_avg_purchase_rate"),
        ("exchange", "0002_purchase"),
        ("orders", "0003_alter_order_id_orderprofit"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="referral_amount",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                max_digits=15,
                verbose_name="Накопления за рефералов",
            ),
        ),
        migrations.CreateModel(
            name="ReferralTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("earn", "Начисление"),
                            ("withdrawal", "Выплата"),
                            ("adjustment", "Корректировка"),
                        ],
                        max_length=20,
                        verbose_name="Тип операции",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4, max_digits=15, verbose_name="Сумма"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Примечание")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="branches.branch",
                        verbose_name="Филиал",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exchange.currency",
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referral_transactions",
                        to="orders.order",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "referred_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referred_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Реферал",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Реферальная транзакция",
                "verbose_name_plural": "Реферальные транзакции",
                "db_table": "referral_transactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "order"], name="referral_tr_user_id_6dfef8_idx"
                    )
                ],
            },
        ),
    ]
