# Generated by Django 5.0.14 on 2025-07-17 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="referral_code",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Реферальный код",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "Пользователь"),
                    ("operator", "Оператор"),
                    ("admin", "Администратор"),
                    ("owner", "Владелец"),
                ],
                default="user",
                max_length=20,
                verbose_name="Роль",
            ),
        ),
    ]
