# Generated by Django 5.0.2 on 2025-06-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supabase_user_id',
            field=models.CharField(blank=True, help_text='UUID пользователя в Supabase', max_length=255, null=True, unique=True, verbose_name='Supabase User ID'),
        ),
    ]
