# Generated by Django 5.1.4 on 2024-12-24 22:58

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+1239990000000'", regex='^\\+[1-9]\\d{0,2}\\d{10}$')], verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Referral balance'),
        ),
    ]
