# Generated by Django 5.0.14 on 2025-07-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_update_referral_code_null"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="referral_code",
            field=models.CharField(
                default="",
                help_text="Уникальный реферальный код пользователя",
                max_length=20,
                unique=True,
                verbose_name="Реферальный код",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="telegram",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Telegram"
            ),
        ),
    ]
