# Generated by Django 5.0.14 on 2025-07-16 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    models.CharField(blank=True, max_length=100, verbose_name="Страна"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Город"),
                ),
                (
                    "street",
                    models.CharField(blank=True, max_length=200, verbose_name="Улица"),
                ),
                (
                    "house_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Номер дома"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Почтовый индекс"
                    ),
                ),
                (
                    "full_address",
                    models.TextField(blank=True, verbose_name="Полный адрес"),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Широта",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Долгота",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
            ],
            options={
                "verbose_name": "Адрес",
                "verbose_name_plural": "Адреса",
                "db_table": "addresses",
            },
        ),
        migrations.CreateModel(
            name="CurrencyMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("deposit", "Пополнение"),
                            ("withdrawal", "Списание"),
                            ("correction", "Корректировка"),
                        ],
                        max_length=20,
                        verbose_name="Тип движения",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4, max_digits=15, verbose_name="Сумма"
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="Причина")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="currency_movements",
                        to="branches.branch",
                        verbose_name="Филиал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Движение валюты",
                "verbose_name_plural": "Движения валют",
                "db_table": "currency_movements",
                "ordering": ["-created_at"],
            },
        ),
    ]
