# Generated by Django 5.0.14 on 2025-07-14 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0003_branchcurrency_avg_purchase_rate"),
        ("core", "0001_initial"),
        ("exchange", "0002_purchase"),
        ("orders", "0003_alter_order_id_orderprofit"),
        ("users", "0002_user_referral_amount_referraltransaction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrencyMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("deposit", "Пополнение"),
                            ("withdrawal", "Списание"),
                            ("correction", "Корректировка"),
                        ],
                        max_length=20,
                        verbose_name="Тип движения",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4, max_digits=15, verbose_name="Сумма"
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="Причина")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="currency_movements",
                        to="branches.branch",
                        verbose_name="Филиал",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exchange.currency",
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="orders.order",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="exchange.purchase",
                        verbose_name="Закупка",
                    ),
                ),
                (
                    "referral_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.referraltransaction",
                        verbose_name="Реферальная транзакция",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Движение валюты",
                "verbose_name_plural": "Движения валют",
                "db_table": "currency_movements",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["branch", "currency", "user"],
                        name="currency_mo_branch__308369_idx",
                    )
                ],
            },
        ),
    ]
