# Generated by Django 5.0.14 on 2025-07-16 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("exchange", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="currencymovement",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="exchange.currency",
                verbose_name="Валюта",
            ),
        ),
    ]
