# Generated by Django 5.0.14 on 2025-07-15 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_currencymovement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="full_address",
            field=models.TextField(blank=True, verbose_name="Полный адрес"),
        ),
    ]
