# Generated by Django 5.0.14 on 2025-07-16 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="currencymovement",
            name="referral_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.referraltransaction",
                verbose_name="Реферальная транзакция",
            ),
        ),
        migrations.AddField(
            model_name="currencymovement",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddIndex(
            model_name="currencymovement",
            index=models.Index(
                fields=["branch", "currency", "user"],
                name="currency_mo_branch__308369_idx",
            ),
        ),
    ]
