# Generated by Django 5.0.14 on 2025-07-22 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="full_address",
        ),
    ]
